import type { GetServerSideProps, InferGetServerSidePropsType, NextPage } from 'next'
import Head from 'next/head'
import Layout from '../components/layout'
import Homepage from '../components/home'
import axios from './../utility/axios';
import { Ride } from './../utility/interface';

export const getServerSideProps: GetServerSideProps = async () => {
  const getUser = axios.get('/user');
  const getRides = axios.get('/rides');

  let [{ data: user }, { data: rides }] = await Promise.all([getUser, getRides]);

  rides = rides.map((ride: Ride) => {
    let closestStation = ride
      .station_path
      .reduce((s1: number, s2: number) =>
        Math.abs(s2 - user.station_code) < Math.abs(s1 - user.station_code)
          ? s2 : s1
      );

    return {
      ...ride,
      distance: Math.abs(closestStation - user.station_code),
      closest_station: closestStation
    };
  }).sort((r1: Ride, r2: Ride) => r1.distance - r2.distance);

  // will be passed to the page component as props
  return {
    props: {
      user: user,
      rides: rides
    },
  }
}

const Home: NextPage = ({ user, rides }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <>
      <Head>
        <title>Edvora Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout user={user} main={<Homepage rides={rides} userStation={user.station_code} />} />
    </>
  )
}

export default Home
